#!/bin/bash

#Verify openSuse Version
cat /etc/SuSE-release

#Install docker on openSuse
sudo zypper in docker
sudo systemctl start docker
sudo docker run hello-world
sudo systemctl enable docker
sudo /usr/sbin/usermod -a -G docker vagrant 
